openelections/openelections-data-tx

- 2016/20160301__tx__primary__cochran__precinct.csv
Verified President totals. Cochran County is so small that simply checking the Presidential totals and results of the Democratic referenda was enough for me to be confident in the correctness of the results.
> Add precinct-level results for the 2016 primaries in Cochran County

- 2016/20160301__tx__primary__angelina__precinct.csv
The .ASC file in the sources repository was missing half the Republican primary races and all the Democratic primary races.
I had to use OCR on the canvass report to parse these results, and there were handwritten corrections that I incorporated as well.
I've verified that totals for each race add up to what was printed on the top of the canvass report.
The second page of the canvass report, with the results for the Republican presidential primary election, was missing, and I could not locate it; as such, that data is not present in this PR.
> Add precinct-level results for the 2016 primaries in Angelina County

- 2016/20160301__tx__primary__lipscomb__precinct.csv
This one was strange - halfway through the source file, the race names all became "Justice, Supreme Court, Place {3,4,5,6,7,8...}", as if Excel's Auto Fill feature were used.
I matched candidate names with the correct races. Thank goodness for VLOOKUP.
> Add precinct-level results for the 2016 primaries in Lipscomb County

- 2016/20160301__tx__primary__howard__precinct.csv
The source data file only gave results in blocks of 1-6 precincts. They are as follows:
|Precinct Groups|
|-|
11, 12, 12a, 13, 14, 16
103, 104, 105
24, 25, 26
205
207, 207c
208
32, 33, 34, 35
304
42, 45, 46
404, 405
408
409
> Add precinct-level results for the 2016 primaries in Howard County

- 2016/20160301__tx__primary__armstrong__precinct.csv
The Democratic primary results are a mess: two precincts are missing from the data, and none of the totals match the SoS's data. It would appear that only early vote results were reported to the SoS. The 3 poor Election Day Democratic voters apparently, therefore, were not counted.
The source file did not differentiate mail/absentee ballots by precinct; I created a separate entry per race with precinct "Mail".
> Add precinct-level results for the 2016 primaries in Armstrong County

- 2016/20160301__tx__primary__hill__precinct.csv
This county was a bit special - it broke out votes by `ABSENTEE`, `EV PAPER`, `EV IVO` (iVotronic), `ED PAPER`, and `ED IVO`.
I've listed them as `absentee`, `early_voting_paper`, `early_voting_dre` (direct recording electronic), `election_day_paper`, and `election_day_dre`, respectively.
If you want to consolidate them, just let me know.
BTW: a number of my PRs today have not matched the SoS's data, but have matched Clarity or the county's data. I have more faith in counties I've converted from ASC flat ascii files.
> Add precinct-level results for the 2016 primaries in Hill County

- 2016/20160301__tx__primary__kleberg__precinct.csv
Precincts 13/14, 22/23, 33/34, and 41/42 are lumped together.
> Add precinct-level results for the 2016 primaries in Kleberg County

- 2016/20160301__tx__primary__swisher__precinct.csv
I accidentally neglected quotation marks when reformatting this judicial race name. This PR fixes it.
> Properly quote judicial race name

- 2016/20160301__tx__primary__angelina__precinct.csv
- 2016/20160301__tx__primary__baylor__precinct.csv
- 2016/20161108__tx__general__garza__precinct.csv
Angelina and Baylor had an invisible [byte order mark](https://en.wikipedia.org/wiki/Byte_order_mark) as the first character.
Garza had incorrect header fields.
> Fix up malformed CSV headers

- 2016/20160301__tx__primary__cherokee__precinct.csv
The Total Voters figure in the PDF for Precinct 12 in the Republican primary was inaccurate, showing 509 ballots cast; every summation of individual vote figures resulted in 490. I've overridden the "Ballots Cast" total on row 1792 to reflect the calculated sum.
> Add precinct-level results for the 2016 primaries in Cherokee County

- 2018/20181106__tx__general__guadalupe__precinct.csv
This county used GEMS. Thankfully, it only took 18 minutes to process using `gems.py` (modified, because the format was slightly different), as opposed to the four hours Collin County took.
> Add precinct-level results for the 2018 general election in Guadalupe County

- 2018/20181106__tx__general__tom_green__precinct.csv
This county used Hart (non-Verity) software. `pdf.py` was used to parse.
> Add precinct-level results for the 2018 general election in Tom Green County

- 2018/20181106__tx__general__galveston__precinct.csv
These data files, frustratingly, have header fields for fields that aren't actually present (registered voters, over/undervotes).
> Add precinct-level results for the 2018 general election in Galveston County

- 2018/20181106__tx__general__wichita__precinct.csv
How troublesome.
This was a old-style Hart precinct PDF, parsed using Ghostscript and `pdf.py`.
Ballots cast + overvotes + undervotes did not equal the listed "Ballots Cast" number for precincts 302 and 401. For those precincts, I listed the calculated EV/ED ballots cast, but it does not sum to the total ballots cast (in the `votes` field).
> Add precinct-level results for the 2018 general election in Wichita County

- 2018/20181106__tx__general__randall__precinct.csv
How strange.
This was a CSV file reminiscent of the `csv-a.py` format, but with some notable exceptions:
- No over/undervote information
- No information on ballots cast
- Statistics on provisionals cast and accepted ("Provisional Ballots{, Counted}")
- No total vote numbers (Can be derived, but not verified)
> Add precinct-level results for the 2018 general election in Randall County

- 2018/20181106__tx__general__kerr__precinct.csv
Common spreadsheet format. 
Strangely, only precincts 308 and 405 had numbers for registered voters.
> Add precinct-level results for the 2018 general election in Kerr County

- 2018/20181106__tx__general__waller__precinct.csv
I would have preferred for the county to have the Verity precinct-level PDF available than what they gave, which is a spreadsheet reminiscent of Randall County's.
> Add precinct-level results for the 2018 general election in Waller County

- 2018/20181106__tx__general__edwards__precinct.csv
How frustrating.
The ASC file provided gave only race ID, candidate ID, precinct ID, and vote groups. I was able to deduce the correct races and orders using the SoS's results page and knowledge of other counties' orderings (read: the order in which ES&S sorts races and candidates).
Kendall County is in the 4th Court of Appeals District, along with Edwards County, so I took non-legislative and non-local races from that file. Legislative races were found on the SoS's page, and local races were found by inspecting the sample ballots on the Edwards County web site.
> Add precinct-level results for the 2018 general election in Edwards County

- 2018/20181106__tx__general__brown__precinct.csv
Brown County, though it uses Hart HVS, does not include statistics on over/undervotes.
As such, I can't get accurate numbers on ballots cast by type per precinct.
> Add precinct-level results for the 2018 general election in Brown County

- 2018/20181106__tx__general__comal__precinct.csv
Clarity again had no information on over and undervotes.
Precincts 104, 107, 205, 206, and 402 are missing information on registered voters.
> Update precinct-level results for the 2018 general election in Comal County

- 2018/20180306__tx__primary__young__precinct.csv
The file `2018/20180306__tx__primary__young__precinct.csv` has records where the office has a `\r`but it should really be a space.  Or are we okay with multiline values in records?
> 2018 Young primary - Many records have a \r that should really be a space.

- 2018/20180306__tx__primary__lubbock__precinct.csv
- 2018/20180306__tx__primary__young__precinct.csv
The file `2018/20180306__tx__primary__lubbock__precinct.csv` has records where the office has `\n` character, but it should really be a space.  Or are we okay with multiline values in records?
> 2018 Lubbock primary - fix extra carriage return chars

- 2020/20200303__tx__primary__burleson__precinct.csv
Burleson County reported to the SoS that Elianor Vessali received 372 votes in the Republican primary for TX-17, but their precinct results file shows that she received 382.
> Add precinct-level results for the 2020 primary election in Burleson County

- 2020/counties/20201103__tx__general__mclennan__precinct.csv
It's been quite a while since I've had to deal with precinct result files in the old Hart HVS format - cumulative report has candidate party info, but precinct report does not; I'd forgotten how *fun* that is.
> Add precinct-level results for the 2020 general election in McLennan County

- 2014/counties/20140304__tx__primary__hays__precinct.csv
This fixes a few issues with the 2014 Hays primary file:
* Replace tabs with spaces.
* Remove extra columns.
> Remove tabs and extra columns from 2014 Hays primary file

- 2012/counties/20121106__tx__general__burnet__precinct.csv
- 2012/counties/20121106__tx__general__callahan__precinct.csv
- 2012/counties/20121106__tx__general__castro__precinct.csv
- 2012/counties/20121106__tx__general__concho__precinct.csv
- 2012/counties/20121106__tx__general__dewitt__precinct.csv
- 2012/counties/20121106__tx__general__eastland__precinct.csv
- 2012/counties/20121106__tx__general__grimes__precinct.csv
- 2012/counties/20121106__tx__general__hunt__precinct.csv
- 2012/counties/20121106__tx__general__marion__precinct.csv
- 2012/counties/20121106__tx__general__wilbarger__precinct.csv
- 2018/counties/20181106__tx__general__shackelford__precinct.csv
This removes an extra column that appeared in the "Ballots Cast" rows in several files.
> Remove extra column from "Ballots Cast" rows

- 2018/counties/20180306__tx__primary__blanco__precinct.csv
- 2018/counties/_20180306__tx__primary__stonewall__precinct.csv
This fixes some parsing errors that resulted in some incorrect vote values.
The [2018 Blanco County primary source file](https://github.com/openelections/openelections-sources-tx/blob/0894ee5e2ed07bd98dbe0c4181166ae1caa17583/2018/primary/Blanco%2020180327104145.pdf) contains the following for the number of registered voters:
The [2014 Stonewall County primary source file](https://github.com/openelections/openelections-sources-tx/blob/0894ee5e2ed07bd98dbe0c4181166ae1caa17583/2018/primary/Stonewall%20Dem%20combined%20total%20prect.%202.pdf) contains the following results for George P. Bush and Rick Range in Precinct 2:
> Fix non-integer votes

- 2014/counties/20141104__tx__general__foard__precinct.csv
- 2014/counties/20141104__tx__general__matagorda__precinct.csv
This fixes a spelling error in a candidate name.  The [correct spelling](https://ballotpedia.org/Rocky_Palmquist) is Pal**m**quist.
> Fix spelling error in candidate name

- 2018/counties/_20180306__tx__primary__haskell__precinct.csv
This adds back some values that were accidentally removed in revision 0519b8b534.
Note that these are duplicate entries (in addition to several others) for Stefano de Stefano IV in Precinct 7, which will need to be reconciled separately.
> Add back erroneously removed votes

- 2018/counties/_20180306__tx__primary__haskell__precinct.csv
The "Early" entries are not necessary, and the "Box X" entries are already captured as the precinct.
> Remove redundant columns with empty headers

- 2020/counties/20201103__tx__general__brewster__precinct.csv
This fixes an incorrect vote value, which could have been the result of an OCR error.  According to the [source file](https://github.com/openelections/openelections-sources-tx/blob/0894ee5e2ed07bd98dbe0c4181166ae1caa17583/2020/general/Brewster%20TX%20General-Election-November-3-2020-Canvass-of-Vote-Totals.pdf), Mary "MJ" Hegar received 46 votes in Precinct 1:
> Fix incorrect vote in 2020 Brewster County general file

- 2020/counties/20200303__tx__primary__bosque__precinct.csv
According to the [source file](https://github.com/openelections/openelections-sources-tx/blob/0894ee5e2ed07bd98dbe0c4181166ae1caa17583/2020/primary/BOSQUE_COUNTY-2020_MARCH_3RD_DEMOCRATIC_PRIMARY_332020-Dem.pdf), there were no provisional votes in Bosque County in this election.
> Fix provisional votes in 2020 Bosque County primary file

- 2020/counties/20201103__tx__general__kleberg__precinct.csv
According to the [source file](https://github.com/openelections/openelections-sources-tx/blob/0894ee5e2ed07bd98dbe0c4181166ae1caa17583/2020/general/Kleberg%20TX%202020%20General.pdf), the correct number of mail under votes should be `0`:
> Fix incorrect vote value in 2020 Klebert County general file

- 2020/counties/20201103__tx__general__taylor__precinct.csv
This was likely caused by an OCR error.  According to the [source file](https://github.com/openelections/openelections-sources-tx/blob/0894ee5e2ed07bd98dbe0c4181166ae1caa17583/2020/general/Taylor%20TX%20Official%20Precinct%20results%20301-0%20through%20308-B.pdf), Katija "Kat" Gruene received 2 election day votes:
> Fix incorrect vote value in 2020 Taylor County general file

- 2020/counties/20201103__tx__general__karnes__precinct.csv
This fixes an incorrect value in the 2020 Karnes County general file.  According to the [source file](https://github.com/openelections/openelections-sources-tx/blob/0894ee5e2ed07bd98dbe0c4181166ae1caa17583/2020/general/Karnes%20TX%20precinct%202020.pdf), Donald TTrump received 2 absentee votes:
> Fix values in 2020 Karnes County general file

- 2020/counties/20201103__tx__general__yoakum__precinct.csv
This fixes an incorrect value in the 2020 Yoakum County general file.  According to the [source file](https://github.com/openelections/openelections-sources-tx/blob/0894ee5e2ed07bd98dbe0c4181166ae1caa17583/2020/general/YOAKUM_COUNTY-2020_NOVEMBER_3RD_GENERAL_ELECTION_1132020-2020%20General%20Election%20PRCT.pdf), there were 0 election day undervotes:
> Fix values in 2020 Yoakum County general file

- 2020/counties/20201103__tx__general__lynn__precinct.csv
This fixes an incorrect value in the 2020 Lynn County general file.  According to the [source file](https://github.com/openelections/openelections-sources-tx/blob/0894ee5e2ed07bd98dbe0c4181166ae1caa17583/2020/general/LYNN_COUNTY-2020_NOVEMBER_3RD_GENERAL_ELECTION_1132020-20201115151646.pdf), Tom Watson received 33 early voting votes:
> Fix values in 2020 Lynn County general file

- 2012/counties/20121106__tx__general__live_oak__precinct.csv
This fixes an incorrect value in the 2012 Live Oak County general file.  According to the [source file](https://github.com/openelections/openelections-sources-tx/blob/0894ee5e2ed07bd98dbe0c4181166ae1caa17583/2012/General/LIVE_OAK_COUNTY-2012_General_Election_1162012-2012%20pct%20report%20(1).pdf), Ann Mathews received 99 total votes:
> Fix values in 2012 Live Oak County general file

- 2020/counties/20201103__tx__general__hood__precinct.csv
This fixes some incorrect values in the 2020 Hood County general file. Many of these changes correct a possible OCR issue, where a `5` is supposed to be a `6`:
According to the [source file](https://github.com/openelections/openelections-sources-tx/blob/0894ee5e2ed07bd98dbe0c4181166ae1caa17583/2020/general/HOOD_COUNTY-2020_NOVEMBER_3RD_GENERAL_ELECTION_1132020-November%203%202020%20pct%20by%20pct.pdf),
* The total ballots cast in Precinct 16 should be `4864`:
* David B. Collins received `14` total votes in Precinct 16:
* August Pfluger received `265` total votes in Precinct 15:
* There were `56` undervotes in the US House District 60 race in Precinct 15:
* The total ballots cast in Precinct 14 should be `2606`:
* Mary "MJ" Hegar received `456` total votes in Precinct 14:
* Joseph Biden …
> Fix values in 2020 Hood County primary file

- 2016/counties/20161108__tx__general__anderson__precinct.csv
This fixes some incorrect values in the 2016 Anderson County general file. According to the [source file](https://github.com/openelections/openelections-sources-tx/blob/0894ee5e2ed07bd98dbe0c4181166ae1caa17583/2016/2016%20ANDERSON%20TX%20%20General%20PctxPct.xlsx), the early voting and election day values are correct.  The total votes were simply incorrect:
> Fix values in 2016 Anderson County primary file

- 2018/counties/20181106__tx__general__aransas__precinct.csv
This fixes some incorrect values in the 2018 Aransas County general file. According to the [source file](https://github.com/openelections/openelections-sources-tx/blob/0894ee5e2ed07bd98dbe0c4181166ae1caa17583/2018/general/Aransas%20TX%202018%20general.pdf), Matt Pina received 19 total votes in Precinct 4A:
> Fix values in 2018 Aransas County primary file

- 2020/counties/20200303__tx__primary__hall__precinct.csv
This fixes some incorrect values in the 2020 Hall County general file. According to the [source file](https://github.com/openelections/openelections-sources-tx/blob/0894ee5e2ed07bd98dbe0c4181166ae1caa17583/2020/primary/HALL_COUNTY-2020_MARCH_3RD_REPUBLICAN_PRIMARY_332020-Primary%2003.03.2020%20Precint%20Reporting%20Republican.xlsx), the early voting values for John Cornyn and Virgil Bierschwale should be
and the election day values for the U.S. House District 13 race should be
In both cases, it appears that the previous values were read from the wrong column.
> Fix values in 2020 Hall County primary file

- 2016/counties/20161108__tx__general__wilson__precinct.csv
This fixes some incorrect values in the 2016 Wilson County general file. According to the [source file](https://github.com/openelections/openelections-sources-tx/blob/0894ee5e2ed07bd98dbe0c4181166ae1caa17583/2016/2016%20Wilson,%20TX%20precinct-level%20election%20results.pdf),
* Gary Johnson received `0` mail votes in Precinct 205:
* Wayne Christian received `1339` total votes in Precinct 415:
* The total votes for Wayne Christian and Grady Yarbrough were not updated to reflect the handwritten corrections to the election day votes (see issue #378):
This fixes #378.
> Fix values in 2016 Wilson County general file

- 2018/counties/20181106__tx__general__hardin__precinct.csv
This fixes some incorrect values in the 2018 Hardin County general file. According to the [source file](https://github.com/openelections/openelections-sources-tx/blob/0894ee5e2ed07bd98dbe0c4181166ae1caa17583/2018/general/Hardin%20TX%20precinct2018.pdf),
* Glenn Hegar received `395` total votes in Precinct 7 - ISD:
* Miguel Suazo received `39` election day votes in Precinct `6`:
> Fix values in 2018 Hardin County general file

- 2018/counties/20180306__tx__primary__kimble__precinct.csv
This fixes an issue in the 2018 Kimble County primary file, where the total ballots cast appeared in the wrong column.
> Fix values in 2018 Kimble County primary file

- 2020/counties/20200303__tx__primary__glasscock__precinct.csv
This fixes some incorrect values in the 2020 Glasscock County primary file. According to the [source file](https://github.com/openelections/openelections-sources-tx/blob/0894ee5e2ed07bd98dbe0c4181166ae1caa17583/2020/primary/Glasscock%20TX%20Primary.pdf), 
* Joe Walsh received `1` total vote in Precinct 2:
* Mark Yancey received `3` total votes in Precinct 2:
> Fix values in 2020 Glasscock County primary file

- 2020/counties/20200303__tx__primary__dawson__precinct.csv
This fixes some incorrect values in the 2020 Dawson County primary file. According to the [source file](https://github.com/openelections/openelections-sources-tx/blob/0894ee5e2ed07bd98dbe0c4181166ae1caa17583/2020/primary/DAWSON_COUNTY-2020_MARCH_3RD_REPUBLICAN_PRIMARY_332020-REPUBLICAN%20REPORT.pdf), there were `64` early undervotes for the State Senate race in Precinct 1:
> Fix values in 2020 Dawson County primary file

- 2020/counties/20201103__tx__general__wilbarger__precinct.csv
This fixes some incorrect values in the 2020 Wilbarger County general file. According to the [source file](https://github.com/openelections/openelections-sources-tx/blob/0894ee5e2ed07bd98dbe0c4181166ae1caa17583/2020/general/Wilbarger%20TX%202020%20General.pdf), there `0` election day undervotes for the Senate race in Precinct 21 GEN-ONLY:
> Fix values in 2020 Wilbarger County general file

- 2016/counties/20161108__tx__general__uvalde__precinct.csv
This fixes some incorrect values in the 2016 Uvalde County general file. According to the [source file](https://github.com/openelections/openelections-sources-tx/blob/0894ee5e2ed07bd98dbe0c4181166ae1caa17583/2016/Uvalde_2016_Gen_Elec_part1.tif), 
* Evan McMullin received `0` election day votes in Precinct 1:
* The total votes in Precinct 6 for the presidential race should be:
> Fix values in 2016 Uvalde County general file

- 2016/counties/20160301__tx__primary__jim_wells__precinct.csv
This fixes some incorrect values in the 2016 Jim Wells County primary file. According to the [source file](https://github.com/openelections/openelections-sources-tx/blob/0894ee5e2ed07bd98dbe0c4181166ae1caa17583/2016/Jim%20Wells%20TX%202016%20pRIMARY%20dEM%20cANVASS%20rEPORT.pdf), the correct values are:
> Fix values in 2016 Jim Wells County primary file

- 2018/counties/20181106__tx__general__sterling__precinct.csv
This fixes some incorrect values in the 2018 Sterling County general file. According to the [source file](https://github.com/openelections/openelections-sources-tx/blob/0894ee5e2ed07bd98dbe0c4181166ae1caa17583/2018/general/Sterling%20TX%20general.pdf), the total number of votes cast in Precinct 1 for the Senate seat should be `137`:
This also fixes the congressional district for the House race.  It should be `11`, not `1`:
> Fix values in 2018 Sterling County general file

- 2016/counties/20161108__tx__general__lamb__precinct.csv
This fixes some incorrect values in the 2016 Lamb County general file. According to the [source file](https://github.com/openelections/openelections-sources-tx/blob/0894ee5e2ed07bd98dbe0c4181166ae1caa17583/2016/Lamb%20TX%20November%208th,%202016%20Precinct%20by%20Precinct%20report.pdf), there were `5` total Democratic straight party votes in the Springlake 1st Baptist Precinct:
> Fix values in 2016 Lamb County general file

- 2016/counties/20161108__tx__general__bosque__precinct.csv
This fixes some incorrect values in the 2016 Bosque County general file. According to the [source file](https://github.com/openelections/openelections-sources-tx/blob/0894ee5e2ed07bd98dbe0c4181166ae1caa17583/2016/2016%20bosque.pdf), Loren Marc Schneiderman received `14` election day and `2` early voting votes in Precinct 10:
> Fix values in 2016 Bosque County general file

- 2016/counties/20161108__tx__general__upton__precinct.csv
This fixes some incorrect values in the 2016 Upton County general file. According to the [source file](https://github.com/openelections/openelections-sources-tx/blob/0894ee5e2ed07bd98dbe0c4181166ae1caa17583/2016/UPTON_COUNTY-2016_General_Election_1182016-CANVASSING_VOTES_Precinct..Report.Nov.16_GE_11.16.16.pdf),
* Pete P. Gallego received `0` provisional votes in Precinct 1:
> Fix values in 2016 Upton County general file

- 2018/counties/20181106__tx__general__deaf_smith__precinct.csv
The early voting value for Christi Craddick in Precinct 2 was hand-corrected in the [source file](https://github.com/openelections/openelections-sources-tx/blob/0894ee5e2ed07bd98dbe0c4181166ae1caa17583/2018/general/Deaf%20Smith%20TX%202018%20Precinct%20by%20precinct%20returns.pdf) from `322` to `323`.  However, unlike the other hand-corrected values, the total value for this entry was not updated accordingly.
> Fix values in 2018 Deaf Smith County general file

- 2018/counties/20181106__tx__general__duval__precinct.csv
This fixes some incorrect values in the 2018 Duval County general file. According to the [source file](https://github.com/openelections/openelections-sources-tx/blob/0894ee5e2ed07bd98dbe0c4181166ae1caa17583/2018/general/DUVAL_COUNTY-2018_General_Election_1162018-precinct.pdf2018.pdf),
* Beto O'Rourke received `74` total votes in Precinct 6:
* Greg Abbot received `17` election day votes in Precinct 4:
* There were `274` ballots cast in the Attorney General race in Precinct 3:
> Fix values in 2018 Duval County general file

- 2018/counties/20181106__tx__general__lavaca__precinct.csv
This fixes some incorrect values in the 2018 Lavaca County general file. According to the [source file](https://github.com/openelections/openelections-sources-tx/blob/0894ee5e2ed07bd98dbe0c4181166ae1caa17583/2018/general/LAVACA_COUNTY-2018_General_Election_1162018-PCT%20by%20PCT%20report%20with%20group%20detail%20Official.pdf),
* Greg Abbot received `65` early voting machine votes (for a total of `135` early votes) in Precinct 12:
* Mike Wright received `1` early voting paper votes (for a total of `3` early votes) in Precinct 17:
> Fix values in 2018 Lavaca County general file

- 2018/counties/20181106__tx__general__runnels__precinct.csv
This fixes some incorrect values in the 2018 Runnels County general file. According to the [source file](https://github.com/openelections/openelections-sources-tx/blob/0894ee5e2ed07bd98dbe0c4181166ae1caa17583/2018/general/Runnells%20TX%20precinct%202018%20Gen.pdf), Kim Olson received `43` election day votes in Precinct 1:
> Fix values in 2018 Runnels County general file

- 2016/counties/20161108__tx__general__floyd__precinct.csv
This fixes some incorrect values in the 2016 Floyd County general file. According to the [source file](https://github.com/openelections/openelections-sources-tx/blob/0894ee5e2ed07bd98dbe0c4181166ae1caa17583/2016/2016%20Floyd%20County%2C%20TX%20precinct-level%20election%20results.pdf),
* Donald Trump received `32` total votes in Precinct 24B:
* There were `6` election day under votes in the Presidential race in Precinct 1:
* Troy Bonar received `16` total votes, Mark Lawson received `13` total votes, and there were `71` total under votes in the U.S. House District 19 race in Precinct 23:
> Fix values in 2016 Floyd County general file

- 2016/counties/20161108__tx__general__camp__precinct.csv
This fixes some incorrect values in the 2016 Camp County general file. According to the [source file](https://github.com/openelections/openelections-sources-tx/blob/0894ee5e2ed07bd98dbe0c4181166ae1caa17583/2016/CAMP%20TX%20FINAL%20ELECTION%20RESULTS%20by%20PCT%20EL30A.pdf),
* There were `128` early Democratic straight party votes in Precinct 1:
* Gary Johnson received `10` election day votes in Precinct 2:
> Fix values in 2016 Camp County general file

- 2016/counties/20161108__tx__general__karnes__precinct.csv
This fixes some incorrect values in the 2016 Karnes County general file. According to the [source file](https://github.com/openelections/openelections-sources-tx/blob/0894ee5e2ed07bd98dbe0c4181166ae1caa17583/2016/2016%20Karnes%20County%20DOC040417-04042017103526.pdf),
* Gary Johnson received `11` total votes in Precinct 1:
> Fix values in 2016 Karnes County general file

- 2016/counties/20161108__tx__general__duval__precinct.csv
This fixes some incorrect values in the 2016 Duval County general file. According to the [source file](https://github.com/openelections/openelections-sources-tx/blob/0894ee5e2ed07bd98dbe0c4181166ae1caa17583/2016/2016%20duval%20tx.pdf), there were `136` election day straight party under votes in Precinct 2:
> Fix values in 2016 Duval County general file

- 2018/counties/20181106__tx__general__crosby__precinct.csv
This fixes many incorrect values in the 2018 Crosby County general file.
When we fixed the headers in revision 02b6697821f06a70e99cf0937857e28eae5d05b5 ("fixed headers on Crosby general"), we inadvertently rearranged the columns and omitted the total votes.
> Fix values in 2018 Crosby County general file

- 2018/counties/20181106__tx__general__grimes__precinct.csv
This fixes some incorrect values in the 2018 Grimes County general file. According to the [source file](https://github.com/openelections/openelections-sources-tx/blob/0894ee5e2ed07bd98dbe0c4181166ae1caa17583/2018/general/Grimes%20TX%202018%20general%20election%20by%20precinct.pdf), Steven David received `49` total votes in Precinct 2:
> Fix values in 2018 Grimes County general file

- 2020/counties/20200303__tx__primary__bosque__precinct.csv
This fixes some incorrect values in the 2020 Bosque County primary file. According to the [source file](https://github.com/openelections/openelections-sources-tx/blob/0894ee5e2ed07bd98dbe0c4181166ae1caa17583/2020/primary/BOSQUE_COUNTY-2020_MARCH_3RD_DEMOCRATIC_PRIMARY_332020-Dem.pdf),
* Joseph R. Biden received `0` provisional votes in Precinct 5:
* Adrian Ocegueda received `1` total vote in Precinct 11:
* Mark Watson received `8` total votes in Precinct 9:
> Fix values in 2020 Bosque County primary file

- 2020/counties/20201103__tx__general__live_oak__precinct.csv
This fixes some incorrect values in the 2020 Live Oak County general file. According to the [source file](https://github.com/openelections/openelections-sources-tx/blob/0894ee5e2ed07bd98dbe0c4181166ae1caa17583/2020/general/Live%20Oak%20TX%202020%20General.pdf),
* Frank Pomeroy received `592` total votes in Precinct 2:
* Judith Zaffirini received `8` total votes in Precinct 7:
* Marian Knowlton received `567` total votes in Precinct 14:
> Fix values in 2020 Live Oak County general file

- 2014/counties/20141104__tx__general__foard__precinct.csv
This fixes some incorrect values in the 2014 Foard County general file. According to the [source file](https://github.com/openelections/openelections-sources-tx/blob/0894ee5e2ed07bd98dbe0c4181166ae1caa17583/2014/FOARD_COUNTY-2014_General_Election_1142014-Nov%202014%20Gen%20Elect%20Pct%20Rep.pdf),
* Mark A. Miller received `3` total votes in Precinct 301:
* There were `8` early under votes in the Railroad Commissioner race in Precinct 201:
> Fix values in 2014 Foard County general file

- 2018/counties/20181106__tx__general__crosby__precinct.csv
These values actually correspond to the total number of voters in the county, and not the number of registered voters in each precinct.
> Remove misleading entries from 2018 Crosby County general file

- 2014/counties/20141104__tx__general__delta__precinct.csv
This fixes some incorrect values in the 2014 Delta County general file. According to the [source file](https://github.com/openelections/openelections-sources-tx/blob/0894ee5e2ed07bd98dbe0c4181166ae1caa17583/2014/DELTA_COUNTY-2014_General_Election_1142014-Election14.pdf), there were `9` total under votes in the U.S. Senate race in Precinct 7:
> Fix values in 2014 Delta County general file

- 2016/counties/20160301__tx__primary__fisher__precinct.csv
This fixes some incorrect values in the 2016 Fisher County primary file. According to the [source file](https://github.com/openelections/openelections-sources-tx/blob/0894ee5e2ed07bd98dbe0c4181166ae1caa17583/2016/Fisher%20TX%202016%20PRIMARY%20DEM%20%26%20REP.PDF), Hillary Clinton received `49` total votes in Precinct 1:
> Fix values in 2016 Fisher County primary file

- 2016/counties/20161108__tx__general__van_zandt__precinct.csv
This fixes some incorrect values in the 2016 Van Zandt County general file. According to the [source file](https://github.com/openelections/openelections-sources-tx/blob/0894ee5e2ed07bd98dbe0c4181166ae1caa17583/2016/2016%20Van%20Zandt%20County%2C%20TX%20precinct-level%20election%20results.pdf),
* Gary Johnson received `12` election day votes in Precinct 1B:
* Dan Flynn received `41` mail votes in Precinct 2C:
> Fix values in 2016 Van Zandt County general file

- 2016/counties/20161108__tx__general__wilson__precinct.csv
This fixes an incorrect value in the 2016 Wilson County general file.  According to the [source file](https://github.com/openelections/openelections-sources-tx/blob/0894ee5e2ed07bd98dbe0c4181166ae1caa17583/2016/2016%20Wilson,%20TX%20precinct-level%20election%20results.pdf), Donald Trump received `540` total absentee votes:
This does not fix the issues described in #416, so the `early_voting` and `election_day` values for this entry remain flipped.
> Fix non-integer absentee vote in 2016 Wilson County general file
