openelections/openelections-data-tx

- 2016/20161108__tx__general__harrison__precinct.csv
CSV from a PDF with embedded text
> Harrison County TX 2016 precinct results

- 2014/20141104__tx__general__sabine__precinct.csv
This PR adds the general election results for Sabine county, precincts 1 thru 8 and total votes by precinct for November, 2014.
* Not all candidates in the [Race Summary Report (RSS)](http://elections.sos.state.tx.us/elchist175_state.htm) are listed. `party` is left as **NA**.
* `candidate` **Emily “Spicybrown” Sanchez** has the odd quotes around the nickname (this nickname appears in the RSS, also). It has not been modified, but can on guidance. 
* `party` was converted from abbreviated form within the RSS to long-form.
[https://github.com/timtrice/sabine-2014-general-election/commits/26fd76eb609319a17b52edae289edd889fb359d6/sabine-2014-general-election.R](https://github.com/timtrice/sabine-2014-general-election/commits/26fd76eb609319a17b52edae289edd889fb359d6/sabine-2014-general-election …
> Parsed Sabine county 20141104 General ED

- dallas_parser.py
I'm not certain how welcome it would be, but I thought I'd share the code I've been using to parse through Dallas County's results.
Feel free to reject this PR if not desired.
> Dallas County results parser?

- 2016/20160301__tx__primary__harrison__precinct.csv
> added 2016 Precinct Harrison County Primaries

- 2016/20160301__tx__primary__bee__precinct.csv
The votes cast for President have been verified, and totals add up.
This CSV contains total registered voters and ballots cast per precinct, as well as over and under votes per race.
> Add precinct-level results for the 2016 primaries in Bee County

- 2016/20160301__tx__primary__anderson__precinct.csv
I verified enough totals to have confidence in the results.
(The total number of votes for the 3rd Judicial District did not match the Secretary of State's numbers, but it did match what was reported in the source file. Nothing I can do about that.)
> Add precinct-level results for the 2016 primaries in Anderson County

- 2016/20160301__tx__primary__grimes__precinct.csv
Verified largest Presidential totals.
> Add precinct-level results for the 2016 primaries in Grimes County

- 2016/20160301__tx__primary__gaines__precinct.csv
Verified totals for President, as well as individually for HRC, Sanders, Cruz, Trump
> Add precinct-level results for the 2016 primaries in Gaines County

- 2016/20160301__tx__primary__concho__precinct.csv
Verified President vote totals.
Strangely, the source file gave the 4 votes that Mike Huckabee was reported by the Secretary of State as having received to Ted Cruz; SoS numbers are 4/280; source file numbers are 0/284.
Again, nothing I can really do about it, I don't think.
> Add precinct-level results for the 2016 primaries in Concho County

- 2016/20160301__tx__primary__atascosa__precinct.csv
Verified vote totals for President, Railroad Commissioner.
HRC's vote totals were 2 greater than was reported to the Secretary of State, but that's a difference that's present in the source data set. Again, nothing I can do about it.
> Add precinct-level results for the 2016 primaries in Atascosa County

- 2016/20160301__tx__primary__aransas__precinct.csv
I verified that the vote totals matched the Secretary of State's site for President, Railroad Commissioner, and Supreme Court Place 3.
Aransas County's format was identical to Bee County's, which made things easy 😎
> Add precinct-level results for the 2016 primaries in Aransas County

- 2016/20160301__tx__primary__guadalupe__precinct.csv
Atypical source file formats will be the death of me. I'll leave it at that.
> Add precinct-level results for the 2016 primaries in Guadalupe County

- 2016/20160301__tx__primary__comal__precinct.csv
The source file had absentee votes. I merged them in into `early_voting` with early voting by personal appearance. If a separate field for absentee votes is desired, let me know.
> Add precinct-level results for the 2016 primaries in Comal County

- 2016/20160301__tx__primary__wilson__precinct.csv
`provisional` and `absentee` results per precinct were available.
> Add precinct-level results for the 2016 primaries in Wilson County

- 2016/20160301__tx__primary__montgomery__precinct.csv
Results do not agree with the SoS, but do agree with the county's cumulative report.
> Add precinct-level results for the 2016 primaries in Montgomery County

- 2016/20160301__tx__primary__mclennan__precinct.csv
Clinton's votes were reported to the Sec. of State as one fewer than the county total.
Cumulative report from the county agrees with this dataset, though.
> Add precinct-level results for the 2016 primaries in McLennan County

- 2016/20160301__tx__primary__hutchinson__precinct.csv
Amusingly, every Republican "Proposition" was spelled "Proprosition".
> Add precinct-level results for the 2016 primaries in Hutchinson County

- 2016/20160301__tx__primary__austin__precinct.csv
> Add precinct-level results for the 2016 primaries in Austin County

- 2016/20160301__tx__primary__bandera__precinct.csv
The file extension was missing, but it turned out to be a spreadsheet, and even better, in the format that the majority of my PRs have used.
> Add precinct-level results for the 2016 primaries in Bandera County

- 2016/20160301__tx__primary__bandera__precinct.csv
I'd forgotten to include them on the first pass.
> Add party code for Bandera County referenda

- 2016/20160301__tx__primary__austin__precinct.csv
- 2016/20160301__tx__primary__hill__precinct.csv
These two counties' formats were irregular, which caused some difficulties.
This PR fixes some issues that came up as a result.
> Fix unintended district fields

- 2016/20160301__tx__primary__lamar__precinct.csv
Long-format .ASC file; has `provisional` and `absentee` separate.
> Add precinct-level results for the 2016 primaries in Lamar County

- 2016/20160301__tx__primary__leon__precinct.csv
The associations in this file were far easier to figure out than in #81.
> Add precinct-level results for the 2016 primaries in Leon County

- 2016/20160301__tx__primary__mitchell__precinct.csv
`provisional` and `absentee` could very well be switched. There were 2 of one and none of the other.
> Add precinct-level results for the 2016 primaries in Mitchell County

- 2016/20160301__tx__primary__navarro__precinct.csv
It's nice when all the numbers add up for a change.
> Add precinct-level results for the 2016 primaries in Navarro County

- 2016/20160301__tx__primary__nolan__precinct.csv
Note: The source files only had results for state and federal races, and no referenda.
> Add precinct-level results for the 2016 primaries in Nolan County

- 2016/20160301__tx__primary__scurry__precinct.csv
Educated guess that election day > early voting >> absentee > provisional.
> Add precinct-level results for the 2016 primaries in Scurry County

- 2016/20160301__tx__primary__robertson__precinct.csv
No referenda or propositions. No county offices for Democrats. (Were there no Democratic county races, or is the data just incomplete?)
> Add precinct-level results for the 2016 primaries in Robertson County

- CONTRIBUTING.md
This is just a basic proposal, taken from the OpenElections [docs](http://docs.openelections.net/data-entry/#data-entry-guidelines) and discussion on #105.
I did notice that none of the OpenElections repositories have a contributing file. Not certain whether it's strictly necessary, but without it, you get people like me who, albeit possessing good intentions, violate the style guide in a few ways. 😬
> Propose CONTRIBUTING.md

- 2014/20141104__tx__general__rockwall__precinct.csv
- 2014/20141104__tx__general__wood__precinct.csv
- 2016/20160301__tx__primary__fannin__precinct.csv
- 2016/20160301__tx__primary__fayette__precinct.csv
- 2016/20160301__tx__primary__freestone__precinct.csv
- 2016/20160301__tx__primary__hill__precinct.csv
- 2016/20160301__tx__primary__robertson__precinct.csv
- 2016/20160301__tx__primary__wilson__precinct.csv
- 2016/20160301__tx__primary__wood__precinct.csv
- 2016/20161108__tx__general__armstrong__precinct.csv
- 2016/20161108__tx__general__chambers__precinct.csv
- 2016/20161108__tx__general__cochran__precinct.csv
- 2016/20161108__tx__general__collin__precinct.csv
- 2016/20161108__tx__general__coryell__precinct.csv
- 2016/20161108__tx__general__crane__precinct.csv
- 2016/20161108__tx__general__el_paso__precinct.csv
- 2016/20161108__tx__general__fannin__precinct.csv
- 2016/20161108__tx__general__freestone__precinct.csv
- 2016/20161108__tx__general__frio__precinct.csv
- 2016/20161108__tx__general__gonzales__precinct.csv
- 2016/20161108__tx__general__lynn__precinct.csv
- 2016/20161108__tx__general__newton__precinct.csv
- 2016/20161108__tx__general__robertson__precinct.csv
- 2016/20161108__tx__general__throckmorton__precinct.csv
- 2016/20161108__tx__general__wilson__precinct.csv
- 2016/20161108__tx__general__wood__precinct.csv
This is a start to fixing #107, though there's still more work to be done on that front.
> Precinct district fixes

- 2014/20141104__tx__general__hemphill__precinct.csv
2014 Hemphill results had governor mispelled
> Fixing spelling of governor

- 2014/20140304__tx__primary__cherokee__precinct.csv
Finding all sorts of incorrect assumptions in my regular expressions. (Here, that precinct numbers are alphanumeric)
> Add precinct-level results for the 2014 primaries in Cherokee County

- 2014/20140304__tx__primary__aransas__precinct.csv
I now have a workflow for PDF parsing! (well, at least the PDFs in [this](https://i.imgur.com/yGrz9Zt.png) format).
I used [Ghostscript](https://www.ghostscript.com/) to convert the file into a [neat format](https://i.imgur.com/SgwCNNS.png) (`gs -sDEVICE=txtwrite -o output.txt example.pdf`), then I wrote a python script to convert to CSV.
There might be some teething issues (e.g., I discovered issues with the regular expressions I'm using to differentiate line types [notable mention: commas]), but I think that this results file is decent enough.
I'll submit a PR for the `txt->csv` script once I've tested it out on more counties' results, and have made further refinements.
> Add precinct-level results for the 2014 primaries in Aransas County

- 2016/20160301__tx__primary__dawson__precinct.csv
No EV precinct-level results. Similar to another county I did, I included a "Total" precinct with EV/ED distinctions.
> Add precinct-level results for the 2016 primaries in Dawson County

- 2016/20160301__tx__primary__ellis__precinct.csv
Not sure how this slipped past me on my first pass. It's an ASC file, so the code I wrote two months ago should still work. Validated Cruz, Clinton totals.
> Add precinct-level results for the 2016 primaries in Ellis County

- 2018/20180306__tx__primary__andrews__precinct.csv
The source spreadsheet had some annoying errors and inconsistencies (most notably, misspellings of "Precinct" and office names).
> Add precinct-level results for the 2018 primaries in Andrews County

- python-parsers/gems.py
As promised, here is the script I used to parse the PDF whose results are in ddc441f019901bf570548a22315b7ba399d5ff7f.
If further clarification as to usage or function is desired, I'd be happy to provide it.
> Add probably rudimentary parser for GEMS SOVC PDFs

- 2014/20141104__tx__general__williamson__precinct.csv
- python-parsers/exceptions.py
- python-parsers/williamson.py
Adding a parser to read off wilco historical election results and the raw 2014 output
> Add 2014 Williamson County General Results + Wilco Parser

- 2018/20181106__tx__general__brazoria__precinct.csv
Hart Verity - parsed precinct PDF with Camelot, obtained ballots cast + registered voters from canvass PDF.
> Add precinct-level results for the 2018 general election in Brazoria County

- 2018/20181106__tx__general__austin__precinct.csv
A relatively simple fixed-width ASCII file. (Thank goodness.)
> Add precinct-level results for the 2018 general election in Austin County

- 2018/20181106__tx__general__archer__precinct.csv
I think it's a universal truth that you'll always be embarrassed by past code. I found several embarrassing errors in the code I have to parse CSV files, though they're fixed now.
> Add precinct-level results for the 2018 general election in Archer County

- 2018/20181106__tx__general__angelina__precinct.csv
After being in PDF Hell™ for so long, I'd forgotten how good a fixed-width ASCII file could be, even if this one only contained total votes, not votes by type.
> Add precinct-level results for the 2018 general election in Angelina County

- 2018/20181106__tx__general__andrews__precinct.csv
Used openpyxl to walk through the spreadsheet.
> Add precinct-level results for the 2018 general election in Andrews County

- 2018/20181106__tx__general__anderson__precinct.csv
Used openpyxl to walk through the spreadsheet.
> Add precinct-level results for the 2018 general election in Anderson County

- 2018/20181106__tx__general__bell__precinct.csv
I'm not sure if it's good (less processing time) or bad (a lot of effort to decipher small counties' bespoke formats for a piddly number of votes) that all the largest counties have easily accessible results.
> Add precinct-level results for the 2018 general election in Bell County

- 2018/20181106__tx__general__cameron__precinct.csv
Another well-formed ASC file that just worked. These counties really are spoiling me.
> Add precinct-level results for the 2018 general election in Cameron County

- 2018/20181106__tx__general__bell__precinct.csv
This is what I get for relying on the "Precinct Code" field instead of parsing the "Precinct Name" field.
Thanks for catching my mistake, @pullyl!
> Amend precinct names for the 2018 general election in Bell County

- 2016/counties/20161108__tx__general__anderson__precinct.csv
A few races were missing total votes, added those into lines 522, 523, 524
> Fixing total votes for 2016

- 2018/20181106__tx__general__la_salle__precinct.csv
Based on reformatting https://github.com/openelections/openelections-sources-tx/blob/master/2018/general/LASALLE_COUNTY-2018_General_Election_1162018-November%206%2C%202018%20General%20Election.xlsx
> Add lasalle 2018

- 2018/20181106__tx__general__wise__precinct.csv
Again, `csv-a.py` format. Though the race names were all uppercase.
> Add precinct-level results for the 2018 general election in Wise County

- 2018/20181106__tx__general__brazos__precinct.csv
`csv-a.py` was used to parse this county.
There were some interesting precinct + split names, e.g. "1", "1 CSISD", "102 FED 17 5 12"; these are the same as those listed in the Brazos County web site's PDF.
> Add precinct-level results for the 2018 general election in Brazos County

- 2018/20181106__tx__general__ellis__precinct.csv
Another ASC file, though with only one vote group (total).
> Add precinct-level results for the 2018 general election in Ellis County

- 2018/20181106__tx__general__ector__precinct.csv
Another `csv-a.py` spreadsheet.
> Add precinct-level results for the 2018 general election in Ector County

- 2018/20181106__tx__general__taylor__precinct.csv
`csv-a.py` spreadsheet. No registered voters, though.
> Add precinct-level results for the 2018 general election in Taylor County

- 2018/20181106__tx__general__potter__precinct.csv
A strange county with a format similar to `csv-a.py` (though all that really says is that it was well-formed tabular data with columns and headers - the bar for similarity is **very** low), but I had to write a custom parser. If I find another county with the same format, I'll publish it; otherwise, I won't.
> Add precinct-level results for the 2018 general election in Potter County

- 2018/20181106__tx__general__kaufman__precinct.csv
Good: It's a fixed-width ASC file.
Bad: It only has one vote group.
> Add precinct-level results for the 2018 general election in Kaufman County

- 2018/20181106__tx__general__victoria__precinct.csv
An ASC file with five vote groups! Exciting!
> Add precinct-level results for the 2018 general election in Victoria County

- 2018/20181106__tx__general__hunt__precinct.csv
> Add precinct-level results for the 2018 general election in Hunt County

- 2018/20181106__tx__general__orange__precinct.csv
> Add precinct-level results for the 2018 general election in Orange County

- 2018/20181106__tx__general__liberty__precinct.csv
> Add precinct-level results for the 2018 general election in Liberty County

- 2018/20181106__tx__general__henderson__precinct.csv
The usual CSV format. Interestingly, there was a `*DB2.xls` file that contained...2016 general results.
> Add precinct-level results for the 2018 general election in Henderson County

- 2018/20181106__tx__general__coryell__precinct.csv
Again, the usual CSV file format.
> Add precinct-level results for the 2018 general election in Coryell County

- 2018/20181106__tx__general__walker__precinct.csv
A slightly nonstandard CSV file with only EV/ED, no recorded totals or ballots cast or over/under.
> Add precinct-level results for the 2018 general election in Walker County

- 2018/20181106__tx__general__san_patricio__precinct.csv
The same format as Walker County, but different column headers.
> Add precinct-level results for the 2018 general election in San Patricio County

- 2018/20181106__tx__general__harrison__precinct.csv
> Add precinct-level results for the 2018 general election in Harrison County

- 2018/20181106__tx__general__nacogdoches__precinct.csv
Concatenated hospital district, ISD, MUD to the main file (all `csv-a.py` format).
> Add precinct-level results for the 2018 general election in Nacogdoches County

- 2018/20181106__tx__general__cherokee__precinct.csv
The calculated and recorded Ballots Cast numbers for Precinct 48 don't match. I did the same thing as Wichita County and put both the recorded number and the calculated (split into EV/ED) numbers in the file.
> Add precinct-level results for the 2018 general election in Cherokee County

- 2018/20181106__tx__general__briscoe__precinct.csv
Gonna be PRing the rest of the ASC counties tonight.
> Add precinct-level results for the 2018 general election in Briscoe County

- 2018/20181106__tx__general__leon__precinct.csv
An ASC file with EV/ED/absentee/limited/provisional, *and* a county website that associates the vote groups with the field names! 😻
...Weird reaction? Definitely.
> Add precinct-level results for the 2018 general election in Leon County

- 2018/20181106__tx__general__nolan__precinct.csv
Today, I learned that there's a "Multicounty Court at Law" which acts as the County Court-at-Law for Mitchell, Nolan, and Fisher counties. Fascinating.
> Add precinct-level results for the 2018 general election in Nolan County

- 2018/20181106__tx__general__robertson__precinct.csv
Again, I guessed as to the field name correspondences, assuming once again that EV > ED > absentee.
> Add precinct-level results for the 2018 general election in Robertson County

- 2018/20181106__tx__general__scurry__precinct.csv
Did I mention how much I dislike guessing vote fields?
Assumptions:
- Absentee: 244
- Early Voting: 2607
- Election Day: 1539
- Provisional: 1
> Add precinct-level results for the 2018 general election in Scurry County

- 2018/20181106__tx__general__yoakum__precinct.csv
And that's all the easy ASC files from the SoS, it seems.
> Add precinct-level results for the 2018 general election in Yoakum County

- 2018/20181106__tx__general__la_salle__precinct.csv
I appreciate the work you did, @pullyl, but I have a Python parser that takes county results spreadsheets and produces a clean output. Granted, it looks like I didn't actually PR it into the `python-parsers` directory. I'll do that soon.
> Update precinct-level results for the 2018 general election in La Salle County

- 2018/20181106__tx__general__burnet__precinct.csv
Going to be working through the `csv-a.py`-compatible spreadsheets.
> Add precinct-level results for the 2018 general election in Burnet County

- 2018/20181106__tx__general__throckmorton__precinct.csv
Removing decimals, adding quotes around office
> Fixing Throckmorton

- 2018/20181106__tx__general__real__precinct.csv
Need to swap office and county
> Fix column titles for Real

- 2016/counties/20161108__tx__general__bosque__precinct.csv
Candidate and party were in wrong columns, missing vota
> 2016 Bosque Formatting changes

- 2016/counties/20161108__tx__general__brewster__precinct.csv
This is converting `\r` -> `\n`.
> 2016 Brewster general has mac-style line endings, convert to UNIX-style.

- 2018/20180306__tx__primary__milam__precinct.csv
- 2018/20180306__tx__primary__nueces__precinct.csv
- 2018/20181106__tx__general__anderson__precinct.csv
- 2018/20181106__tx__general__gray__precinct.csv
- 2018/20181106__tx__general__shackelford__precinct.csv
This cleans up various data issues in some results files (eg. rows with not enough columns, missing field seperators).
> Cleanup data 2018

- 2020/20200303__tx__primary__angelina__precinct.csv
Texas SoS has, starting from 2019, exposed total results in JSON format, so I can now more easily verify that vote totals for every candidate add up correctly. 🎉
> Add precinct-level results for the 2020 primary election in Angelina County

- python-parsers/rusk_county_2020.py
python parser for the rusk county 2020 primary.  To run it, you will need to add a flag as well as the .pdf.  The flag's to use are either (-d,--dem) for Democrat or (-r,--rep) for republican.  I also included an additional column listing the precinct for the results.
> Rusk county 2020 parser

- 2020/20200303__tx__primary__victoria__precinct.csv
Combined, filtered, and formatted two primary source files:
https://github.com/openelections/openelections-sources-tx/blob/master/2020/primary/VICTORIA_COUNTY-2020_MARCH_3RD_DEMOCRATIC_PRIMARY_332020-DemPctbyPct.xlsx
https://github.com/openelections/openelections-sources-tx/blob/master/2020/primary/VICTORIA_COUNTY-2020_MARCH_3RD_REPUBLICAN_PRIMARY_332020-RepPctbyPctTotals.xlsx
> Created preprocessed file from two sources for 2020-03-03 Victoria County Primary

- 2020/20200303__tx__primary__falls__precinct.csv
Pieced together from source https://github.com/openelections/openelections-sources-tx/blob/master/2020/primary/Falls%20TX%20Precinct%20Results-3-23-2020%2009-18-27%20AM.pdf
Converted from pdf to text:
pdftotext -layout 'Falls TX Precinct Results-3-23-2020 09-18-27 AM.pdf' Falls_TX_Precinct_Results-3-23-2020_09-18-27_AM_preserve_layout.txt
Then used awk to collect office races and glue together into final csv.
> Falls County

- 2020/counties/20201103__tx__general__bell__precinct.csv
The minor misalignment of RV/Ballots Cast rows in this official results PDF threw off my script. Boo.
> Add precinct-level results for the 2020 general election in Bell County

- 2018/counties/20181106__tx__general__san_jacinto__precinct.csv
- 2018/counties/20181106__tx__general__zapata__precinct.csv
- 2020/counties/20200303__tx__primary__kerr__precinct.csv
- 2020/counties/20200303__tx__primary__newton__precinct.csv
This removes unnecessary line breaks that appeared in the middle of a row.
> Remove line breaks that appeared in the middle of a row

- 2018/counties/20180306__tx__primary__trinity__precinct.csv
This removes a leftover merge conflict marker.
> Remove merge conflict marker

- 2012/counties/20121106__tx__general__mitchell__precinct.csv
This file is already utf-8 encoded.
> Remove byte order mark

- 2012/counties/20121106__tx__general__coryell__precinct.csv
- 2012/counties/20121106__tx__general__henderson__precinct.csv
- 2012/counties/20121106__tx__general__kaufman__precinct.csv
- 2012/counties/20121106__tx__general__kerr__precinct.csv
- 2012/counties/20121106__tx__general__liberty__precinct.csv
- 2012/counties/20121106__tx__general__madison__precinct.csv
- 2012/counties/20121106__tx__general__parker__precinct.csv
- 2012/counties/20121106__tx__general__reagan__precinct.csv
- 2012/counties/20121106__tx__general__zapata__precinct.csv
- 2014/counties/20141104__tx__general__bee__precinct.csv
- 2014/counties/20141104__tx__general__callahan__precinct.csv
- 2014/counties/20141104__tx__general__coryell__precinct.csv
- 2014/counties/20141104__tx__general__floyd__precinct.csv
- 2014/counties/20141104__tx__general__hardin__precinct.csv
- 2014/counties/20141104__tx__general__jim_wells__precinct.csv
- 2014/counties/20141104__tx__general__kerr__precinct.csv
- 2014/counties/20141104__tx__general__martin__precinct.csv
- 2014/counties/20141104__tx__general__reagan__precinct.csv
- 2014/counties/20141104__tx__general__roberts__precinct.csv
- 2014/counties/20141104__tx__general__wheeler__precinct.csv
- 2014/counties/20141104__tx__general__willacy__precinct.csv
- 2014/counties/20141104__tx__general__young__precinct.csv
- 2016/counties/20161108__tx__general__denton__precinct.csv
- 2016/counties/20161108__tx__general__jefferson__precinct.csv
- 2016/counties/20161108__tx__general__runnels__precinct.csv
- 2018/counties/20180306__tx__primary__upton__precinct.csv
- 2018/counties/20181106__tx__general__lampasas__precinct.csv
- 2018/counties/20181106__tx__general__martin__precinct.csv
This removes entries that consisted of only non-alphanumeric characters.
> Remove non-alphanumeric entries

- README.md
This adds a badge to indicate the status of format tests.
> Add badge for format tests

- 2020/counties/20201103__tx__general__lamar__precinct.csv
- 2020/counties/20201103__tx__general__willacy__precinct.csv
This fixes a few formatting issues:
* Removes leading and trailing whitespace characters.
* Replaces consecutive whitespace characters with a single space.
> Fix formatting issues

- 2014/counties/20140304__tx__primary__wheeler__precinct.csv
- 2014/counties/20140304__tx__primary__wilbarger__precinct.csv
- 2014/counties/20140304__tx__primary__young__precinct.csv
- 2014/counties/20140304__tx__primary__zapata__precinct.csv
- 2020/counties/20200303__tx__primary__kenedy__precinct.csv
- 2020/counties/20200303__tx__primary__lipscomb__precinct.csv
- 2020/counties/20201103__tx__general__marion__precinct.csv
This fixes several instances where the row for "Registered Voters" contained an inconsistent number of columns.
This concerns #338.
> Fix rows with inconsistent number of columns

- 2018/counties/20180306__tx__primary__brewster__precinct.csv
This removes 2 columns with empty headers that did not contain any meaningful values.
> Remove columns with empty headers

- 2020/counties/20200303__tx__primary__brewster__precinct.csv
This fixes some incorrect values in the 2020 Brewster County primary file. According to the source files ([DEM](https://github.com/openelections/openelections-sources-tx/blob/0894ee5e2ed07bd98dbe0c4181166ae1caa17583/2020/primary/Brewster%20TX%20DEM%20Official-Canvassed-on-3-1-2020-Brewster-County-Democratic-Exec-Committee.pdf), [REP](https://github.com/openelections/openelections-sources-tx/blob/0894ee5e2ed07bd98dbe0c4181166ae1caa17583/2020/primary/Brewster%20TX%20REP%20Official-Canvasses-on-3-12-2020-Brewster-County-Republican-Exec-Committee-1.pdf)),
* Tulsi Gabbard's total votes should be:
* Mary "MJ" Hegar received `23` total votes in Precinct 8:
* Peter P. "Pete" Flores received `61` total votes in Precinct 6:
> Fix values in 2020 Brewster County primary file

- 2012/counties/20121106__tx__general__mcmullen__precinct.csv
This fixes some inconsistent total votes in the 2012 McMullen County general file.
> Fix values in 2012 McMullen County general file

- 2016/counties/20161108__tx__general__polk__precinct.csv
This fixes some incorrect values in the 2016 Polk County general file. According to [this source](http://8.2.209.42/election/showdoc.asp?year=2016&docName=2016-11-08-precinct.pdf), Donald J. Trump received `1820` total votes in Precinct 20:
> Fix values in 2016 Polk County general file

- 2018/counties/20180306__tx__primary__kleberg__precinct.csv
This fixes some incorrect values in the 2018 Kleberg County primary file. According to the source files ([DEM](https://github.com/openelections/openelections-sources-tx/blob/0894ee5e2ed07bd98dbe0c4181166ae1caa17583/2018/primary/KLEBERG_COUNTY-2018_Democratic_Party_Primary_Election_362018-Report%20-%20Precinct%20Report%20(Democratic).pdf), [REP](https://github.com/openelections/openelections-sources-tx/blob/0894ee5e2ed07bd98dbe0c4181166ae1caa17583/2018/primary/KLEBERG_COUNTY-2018_Republican_Party_Primary_Election_362018-Report%20-%20Precinct%20Report%20(Republican).pdf)),
* Mary Miller received `8` total votes in Precinct 12:
* George P. Bush received `85` total votes in Precinct 12:
* Mike Collier received `3` election day votes in Precinct 44:
> Fix values in 2018 Kleberg County primary file
